Third assignment
Anastasiiasyvak/DatabaseBeautySalon pull request #2
Opened 2024-03-25 19:07 UTC by Anastasiiasyvak

2024-04-03 08:06 UTC, Ivashchyk requested changes
min issues

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +SELECT *
```suggestion
SELECT <set of columns>
```

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +    SELECT *
```suggestion
    SELECT 1
```

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +    SELECT *
```suggestion
    SELECT 1
```

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +    SELECT *
```suggestion
    SELECT 1
```

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +SELECT *
```suggestion
SELECT <set of columns>
```

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +    SELECT *
```suggestion
    SELECT 1
```

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +    SELECT *
```suggestion
    SELECT 1
```

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +    SELECT *
```suggestion
    SELECT 1
```

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +    SELECT *
```suggestion
    SELECT 1
```

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +    SELECT *
```suggestion
    SELECT 1
```

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +    SELECT *
```suggestion
    SELECT 1
```

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +    SELECT *
```suggestion
    SELECT 1
```

2024-04-03 08:06 UTC, Ivashchyk commented on pa3.sql
> +    SELECT *
```suggestion
    SELECT 1
```

2024-04-04 20:43 UTC, Anastasiiasyvak commented
https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2

On Wed, Apr 3, 2024 at 11:06 AM Anton Ivashchyk ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> min issues
> ------------------------------
>
> In pa3.sql
> <https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2#discussion_r1549077648>
> :
>
> > +
> +-- збільшуємо зарплату працівникам, які надають масаж, на 10%
> +UPDATE employee
> +SET salary = salary * 1.1
> +WHERE id IN (
> +    SELECT id_employee
> +    FROM employee_service
> +    WHERE id_service IN (
> +        SELECT id
> +        FROM service
> +        WHERE name = 'Massage'
> +    )
> +);
> +
> +-- вибираємо всі записи з таблиці appointment, де id_employee відповідає працівникам, які мають позицію "Master of hair styling"
> +SELECT *
>
> ⬇️ Suggested change
>
> -SELECT *
> +SELECT <set of columns>
>
> ------------------------------
>
> In pa3.sql
> <https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2#discussion_r1549078119>
> :
>
> > +    FROM employee_service
> +    WHERE id_service IN (
> +        SELECT id
> +        FROM service
> +        WHERE name = 'Massage'
> +    )
> +);
> +
> +
> +-- 4) EXISTS with non-correlated subqueries result
> +
> +-- Вибираємо всіх клієнтів, які мають хоча б один запис про призначений їм запис
> +SELECT *
> +FROM customer
> +WHERE EXISTS (
> +    SELECT *
>
> ⬇️ Suggested change
>
> -    SELECT *
> +    SELECT 1
>
> ------------------------------
>
> In pa3.sql
> <https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2#discussion_r1549078366>
> :
>
> > +
> +-- 4) EXISTS with non-correlated subqueries result
> +
> +-- Вибираємо всіх клієнтів, які мають хоча б один запис про призначений їм запис
> +SELECT *
> +FROM customer
> +WHERE EXISTS (
> +    SELECT *
> +    FROM appointment
> +    WHERE appointment.id_customer = customer.id
> +);
> +
> +-- Видаляємо всі записи про послуги, які не мають відповідних записів у таблиці services2products
> +DELETE FROM service
> +WHERE NOT EXISTS (
> +    SELECT *
>
> ⬇️ Suggested change
>
> -    SELECT *
> +    SELECT 1
>
> ------------------------------
>
> In pa3.sql
> <https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2#discussion_r1549078684>
> :
>
> > +    WHERE appointment.id_customer = customer.id
> +);
> +
> +-- Видаляємо всі записи про послуги, які не мають відповідних записів у таблиці services2products
> +DELETE FROM service
> +WHERE NOT EXISTS (
> +    SELECT *
> +    FROM services2products
> +    WHERE services2products.service_id = service.id
> +);
> +
> +-- Збільшуємо зарплату всім працівникам, які надають послугу "Massage" на 10%
> +UPDATE employee
> +SET salary = salary * 1.10
> +WHERE EXISTS (
> +    SELECT *
>
> ⬇️ Suggested change
>
> -    SELECT *
> +    SELECT 1
>
> ------------------------------
>
> In pa3.sql
> <https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2#discussion_r1549079212>
> :
>
> > +-- Збільшуємо зарплату всім працівникам, які надають послугу "Massage" на 10%
> +UPDATE employee
> +SET salary = salary * 1.10
> +WHERE EXISTS (
> +    SELECT *
> +    FROM employee_service
> +    INNER JOIN service  ON employee_service.id_service = service.id
> +    WHERE employee_service.id_employee = employee.id
> +    AND service.name = 'Massage'
> +);
> +
> +-- 5) NOT EXISTS with non-correlated subqueries result
> +
> +
> +-- Вибираємо всіх клієнтів, які не зробили жодного платежу
> +SELECT *
>
> ⬇️ Suggested change
>
> -SELECT *
> +SELECT <set of columns>
>
> ------------------------------
>
> In pa3.sql
> <https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2#discussion_r1549079446>
> :
>
> > +WHERE EXISTS (
> +    SELECT *
> +    FROM employee_service
> +    INNER JOIN service  ON employee_service.id_service = service.id
> +    WHERE employee_service.id_employee = employee.id
> +    AND service.name = 'Massage'
> +);
> +
> +-- 5) NOT EXISTS with non-correlated subqueries result
> +
> +
> +-- Вибираємо всіх клієнтів, які не зробили жодного платежу
> +SELECT *
> +FROM customer
> +WHERE NOT EXISTS (
> +    SELECT *
>
> ⬇️ Suggested change
>
> -    SELECT *
> +    SELECT 1
>
> ------------------------------
>
> In pa3.sql
> <https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2#discussion_r1549079630>
> :
>
> > +
> +
> +-- Вибираємо всіх клієнтів, які не зробили жодного платежу
> +SELECT *
> +FROM customer
> +WHERE NOT EXISTS (
> +    SELECT *
> +    FROM appointment
> +    WHERE appointment.id_customer = customer.id
> +);
> +
> +-- Оновлюємо статуси всіх записів у таблиці appointment, які не мають відповідних записів у таблиці payment на 'cancelled'
> +UPDATE appointment
> +SET status = 'cancelled'
> +WHERE NOT EXISTS (
> +    SELECT *
>
> ⬇️ Suggested change
>
> -    SELECT *
> +    SELECT 1
>
> ------------------------------
>
> In pa3.sql
> <https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2#discussion_r1549079897>
> :
>
> > +    WHERE appointment.id_customer = customer.id
> +);
> +
> +-- Оновлюємо статуси всіх записів у таблиці appointment, які не мають відповідних записів у таблиці payment на 'cancelled'
> +UPDATE appointment
> +SET status = 'cancelled'
> +WHERE NOT EXISTS (
> +    SELECT *
> +    FROM payment
> +    WHERE payment.id_appointment = appointment.id
> +);
> +
> +-- Видаляємо всі записи про клієнтів, які не зробили жодного платежу
> +DELETE FROM customer
> +WHERE NOT EXISTS (
> +    SELECT *
>
> ⬇️ Suggested change
>
> -    SELECT *
> +    SELECT 1
>
> ------------------------------
>
> In pa3.sql
> <https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2#discussion_r1549099607>
> :
>
> > +-- Видалення зустрічей, які мають співробітників, які не є адміністраторами
> +DELETE FROM appointment
> +WHERE id_employee NOT IN (
> +    SELECT id
> +    FROM employee
> +    WHERE position = 'Administrator'
> +);
> +
> +
> +-- 9) EXISTS with correlated subqueries result
> +
> +-- Вибірка співробітників, які надають послугу "Manicure" і мають зустрічі
> +SELECT id, name, phone, email, position
> +FROM employee
> +WHERE EXISTS (
> +    SELECT *
>
> ⬇️ Suggested change
>
> -    SELECT *
> +    SELECT 1
>
> ------------------------------
>
> In pa3.sql
> <https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2#discussion_r1549100341>
> :
>
> > +DELETE FROM employee
> +WHERE NOT EXISTS (
> +    SELECT *
> +    FROM appointment
> +    WHERE appointment.id_employee = employee.id
> +);
> +
> +
> +-- 10) NOT EXISTS with correlated subqueries result
> +
> +
> +-- Вибираємр співробітників, які не мають зустрічей
> +SELECT id, name, position
> +FROM employee
> +WHERE NOT EXISTS (
> +    SELECT *
>
> ⬇️ Suggested change
>
> -    SELECT *
> +    SELECT 1
>
> ------------------------------
>
> In pa3.sql
> <https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2#discussion_r1549100564>
> :
>
> > +);
> +
> +-- Оновлення зустрічей зі статусом "pending", які мають клієнтів зі статусом "no show"
> +UPDATE appointment
> +SET status = 'cancelled'
> +WHERE EXISTS (
> +    SELECT *
> +    FROM customer
> +    WHERE customer.id = appointment.id_customer AND customer.status = 'no show'
> +) AND status = 'pending';
> +
> +
> +-- Видалення співробітників, які не мають зустрічей
> +DELETE FROM employee
> +WHERE NOT EXISTS (
> +    SELECT *
>
> ⬇️ Suggested change
>
> -    SELECT *
> +    SELECT 1
>
> ------------------------------
>
> In pa3.sql
> <https://github.com/Anastasiiasyvak/DatabaseBeautySalon/pull/2#discussion_r1549100910>
> :
>
> > +
> +-- Вибираємр співробітників, які не мають зустрічей
> +SELECT id, name, position
> +FROM employee
> +WHERE NOT EXISTS (
> +    SELECT *
> +    FROM appointment
> +    WHERE appointment.id_employee = employee.id
> +);
> +
> +
> +-- Оновлюємо зустрічі зі статусом "pending", які не мають клієнтів
> +UPDATE appointment
> +SET status = 'cancelled'
> +WHERE status = 'pending' AND NOT EXISTS (
> +    SELECT *
>
> ⬇️ Suggested change
>
> -    SELECT *
> +    SELECT 1
>
> ------------------------------
> [...]

2024-04-07 20:26 UTC, merged